### ISSUE TITLE
City Naming Conventions

### ISSUE THREAD

**Issue by LachlanBirdsey** [AIPSE/Models#14]
Using airport codes is not going to work in all cases (e.g. cities without airports)
Suggest using codes from https://www.worldnetlogistics.com/iata-city-airport-codes/ but these are not always logical
Please look and comment @MiraHu @pedrohjn @saapeson

**Comment by pedrohjn** [comment]
I think this is good way to go. And, most cities that should be relevant shall have this codes. On the other hand, big cities may also have more than one airport... 

I found this: https://www.unece.org/cefact/locode/welcome.html It seems more complete....

**Comment by LachlanBirdsey** [comment]
Ah this one seems much better. Examples from UNECE:
FI-HEL, FI-OUL, FI-LPP
DE-BER
AU-ADL 
BR-SAO (instead of GRU)
